// LIST ALL GAMES
const listKiss = () => {
    return [
        'WOLF HUNTERS', 'DRAGON MAIDEN', 'STEAM TOWER', 'SUN WU KONG', 'WITCH', 'FOOTBALL', 'TOP GUN', 'EASTER', 'JIN QIAN WA', 'FORTUNE PANDA', 'ROBIN HOOD', 'ALICE',
        'AFRICAN WILDLIFE', 'SEASONS GREETINGS', 'LAURA', 'AMAZON', 'ALADDIN', 'DOLPHIN', 'PAN JIN LIAN', 'MAGICAL SPIN', 'PIRATE SHIP', 'HALLOWEEN PARTY', 'COOKIE POP',
        'SHINING STARS', 'FAIRY GARDEN', 'STONE AGE', 'WESTERN RANCH STORY', 'MONEY FEVER', 'TREASURE ISLAND', 'GOLDEN TREE', 'RANCH STORY', 'SEA WORLD', 'CIRCUS',
        'FENG SHEN', 'THREE KINGDOM', 'WATER MARGIN', 'GOD OF WEALTH', 'FIVE DRAGON', 'WEALTH', 'AZTEC', 'CRYSTAL', 'GARDEN', 'GREEN LIGHT', 'VICTORY', 'DRAGON GOLD',
        'TALLY HO', 'FORTUNE', 'ORIENT', 'RALLY', 'BOYKING', 'DRAGON', 'SEA CAPTAIN', 'COYOTE CASH', 'T-REX', 'FASHION', 'PAY DIRT', 'FAME', 'BIG SHOT', 'CLEOPATRA',
        'TWISTER', 'GIRLS', 'GOLDEN SLUT', 'EMPEROR GATE', 'ICELAND', 'JAPAN', 'BOXING', 'PANDA', 'INDIA', 'WILD FOX', 'GOLDEN LOTUS', 'PROSPERITY', 'WONG CHOY',
        'HIGH WAY', 'ZHAO CAI JIN BAO', 'GREAT STARS', 'KIMOCHI', 'NIAN NIAN YOU YU', 'CAPTAIN', 'SPARTAN', 'SILVER', 'PANTHER MOON', 'SAFARI HEAT', 'THAI', 'BONUS BEARS',
        'CHERRY LOVE', 'GREAT BLUE', 'IRISH LUCK', 'THE DISCOVERY', 'SPARTA', 'FRUIT', 'GOLDEN TOUR', 'A NIGHT OUT', 'SAMURAI', 'DOLPHIN REEF'
    ]
}

const listMega = () => {
    return [
        'WITCH', 'TOPGUN', 'FOOTBALL', 'EASTER', 'SUNWUKONG', 'JIN QIAN WA', 'FORTUNE PANDA', 'ROBIN HOOD', 'ALICE', 'SEASONS', 'PAN JIN LIAN',
        'MAGICAL SPIN', 'PIRATE SHIP ', 'HALLOWEEN PARTY', 'COOKIE POP', 'SHINING STARS', 'STONE AGE', 'WESTERN RANCH STORY', 'MONEY FEVER', 'TREASURE ISLAND', 'GOLDEN TREE',
        'SEA WORLD', 'RANCH STORY', 'CIRCUS', 'FIVE DRAGON', 'WEALTH', 'AZTEC', 'CRYSTAL', 'GARDEN', 'GREEN LIGHT', 'VICTORY', 'DRAGON GOLD', 'BOYKING', 'SEA CAPTAIN', 'FAME',
        'COYOTE CASH', 'BIG SHOT', 'CLEOPATRA', 'GIRLS', 'PAYDIRT', 'WILD FOX', 'PROSPERITY', 'WONG CHOY', 'HIGH WAY', 'ZHAO CAI JIN BAO', 'GREAT STARS', 'NIAN NIAN YOU YU ',
        'KIMOCHI', 'CAPTAIN', 'GREEN', 'IRISH LUCK', 'GOLDEN LOTUS', 'SPARTAN', 'FRUIT', 'AFRICAN', 'THE DISCOVERY', 'BONUS BEARS', 'GREAT BLUE', 'SAMURAI'
    ]
}

const listPussy = () => {
    return [
        '5 DRAGON', '8 TREASURE 1 QUEEN', 'A NIGHT OUT', 'AFRICAN WILDLIFE', 'ALADDIN', 'ALICE', 'AMAZING THAILAND', 'AGE OF EGYPT', 'AMAZON JUNGLE', 'ARCHER', 'ARCTIC TREASURE',
        'CAPTAIN', 'AZTECS TREASURE', 'BEACH LIFE', 'BERRY BONANZA', 'PROSPERITY', 'BONUS BEAR', 'FORTUNE OF THE FOXS', 'BOYKING', 'BUFFALO BLITZ', 'CAT QUEN', 'BANANA MONKEY',
        'CHERRY LOVE', 'FORTUNE PANDA', 'CIRCUS', 'CAPTAIN TREASURE', 'COYOTE CASH', 'CYRTAL WATER', 'DAMINGDIGUO', 'FOOTBALL CARNOVAL', 'DELOVEMONE', 'GREATSTAR', 'FONGSHEN',
        'DESERT', 'GOLDEN SLUT', 'DOLPHIN REEF', 'DON QUIXOTE', 'DRAGONS', 'EASTER SUPRISE', 'EPIC APE', 'FUNKY FRUITS FARM', 'FAIRY GARDEN', 'GREAT CHINA', 'DRAGON GOLD',
        'BIG SHOT', 'DIAMOND VALLEY', 'FARMERS MARKETS', 'GEISHA GARDEN', 'GOLDEN TOUR', 'EMPEROR GATE', 'FOOTBALL', 'GREATBLUE', 'FEI LONG ZAI TIAN', 'HALLOWEEN PARTY', 'FORTUNE',
        'GAELIC LUCK', 'QUEEN OF WAND', 'FOOTBALL FANS', 'FEICUIGONGJU', 'GHOST OF CHRISTMAS', 'GOD OF WEALTH', 'GOLDEN LOTUS', 'GREENLIGHT', 'GOLDEN TREE', 'HALLOWEEN', 'HIGHWAY',
        'HOLOGRAM WILDS', 'IRISHLUCK', 'JAPAN', 'RANCH STORY', 'HALLOWEEN', 'FORTUNE', 'ROME & GLORY', 'JINQIANWA', 'KIMOCHI', 'KING OF OLYMPUS', 'LAND GOLD', 'ICELAND',
        'MONKEY KING', 'ROBIN HOOD', 'LAURA', 'PANTHER MOON', 'LIE YAN ZUAN SHI', 'THREE KINGDOM', 'LUCKY PANDA', 'PENGUIN VACATION', 'INDIAN', 'TRIPLE TWISTER', 'MAGICAL SPIN',
        'SHERLOCK MYSTERY', 'MONEY FEVER', 'PIRATE SHIP', 'NIANIANYOUYU', 'SEAWORLD', 'THAI TEMPLE', 'ORIENT EXPRESS', 'PAYDIRT', 'SANTA SUPRISE', 'SEA CAPTAIN', 'PHARAOH\'S SECRETS',
        'PIRATE', 'LOTTO MADNESS', 'YUN CONG LONG', 'RALLY', 'RICHES OF CLEOPATRA', 'ROARING WILDS', 'THE DISCOVERY', 'SAFARI HEAT', 'SEASON GREETING', 'SHINNING STARS', 'SI XIANG',
        'WEALTH\'S TREASURE', 'SILENT SAMURAI', 'SILVER BULLETS', 'SPARTAN', 'SPUD REILLY\'S', 'STONEAGE', 'SULTAN GOLD', 'T-REX', 'TALLY HO', 'THAI PARADISE', 'THE PIRAMID OF',
        'RAMESSES', 'TIGER CLAW', 'ZHAO CAI JIN BAO', 'WILD SPIRIT', 'XINPENJINLIAN', 'WONGCHOY', 'STRIPER NIGHT', 'TOP GUN', 'TREASURE ISLAND', 'TRUELOVE', 'VICTORY',
        'WARRIOR GOLD', 'WATER MARGIN', 'WESTERN RANCH STORY', 'WHITE KING', 'WILD FOX', 'XUAN PU LIAN HUAN', 'YU HUANG DA DI', 'ZHAOCAIJINBAO'
    ]
}

const listXe = () => {
    return [
        'OH MY HERO', 'ANCIENT FOREST', 'LICENSE TO WIN', 'BISON RAMPAGE 2', 'GOLD RUSH', 'LUPIN', 'FOOTBALL', 'MONEY', 'JIN QIAN WA', 'FORTUNE PANDA', 'ROBIN HOOD', 'ALICE',
        'AFRICAN WILDLIFE', 'SEASONS GREETINGS', 'LAURA', 'PIRATE', 'AMAZON', 'ALADDIN', 'DOLPHIN', 'JIN PING MAI 2', 'BULLS', 'UNICORN 2', 'MAGICAL SPINS',
        'DA SHENG NAO HAI', 'FAIRY GARDEN PLUS', 'CIRCUS', 'FENG SHEN', 'THREE KINGDOM', 'WATER MARGIN', 'FIVE DRAGON', 'WEALTH TREASURE', 'AZTEC', 'CRYSTAL WATERS',
        'ENCHANTED GARDEN', 'GREEN LIGHT', 'VICTORY', 'POLAR ADVENTURES', 'DRAGON GOLD', 'TALLY HO', 'FORTUNE', 'ORIENT EXPRESS', 'RALLY', 'MYSTICAL DRAGON', 'SEA CAPTAIN',
        'COYOTE CASH', 'T-REX', 'GLAMOUROUS WORLD', 'PAY DIRT', 'FAME', 'BIG SHOT', 'CLEOPATRA', 'TRIPLE TWISTER', 'STRIPPER NIGHT', 'UNICORN 2', 'GOLDEN SLUT', 'ICELAND',
        'JAPAN', 'AMAZING THAILAND', 'GREAT CHINA', 'INDIA', 'GOLDEN LOTUS', 'BIG PROSPERITY', 'WONG CHOY', 'HIGHWAY', 'ZHAO CAI JIN BAO', 'GREAT STARS', 'KIMOCHI', 'TOUCHDOWN 2',
        'NIAN NIAN YOU YU', 'CAPTAINS TREASURE', 'SPARTAN', 'SILVER BULLETS', 'SAFARI HEAT', 'THAI PARADISE', 'GREAT BLUE', 'IRISH LUCK', 'DISCOVERY', 'DOLPHIN REFF'
    ]
}

// EXPORT FUNCTION
export {listKiss, listMega, listPussy, listXe};
