// LIST ALL GAMES
const listKiss = () => {
    return [
        'WITCH', 'TOPGUN', 'FOOTBALL', 'EASTER', 'DASHENGNAOHAI', 'LIKUIPIYU', 'SUNWUKONG', 'JIN QIAN WA', 'FORTUNE PANDA', 'ROBIN HOOD', 'ALICE', 'SEASONS', 'PAN JIN LIAN',
        'MAGICAL SPIN', 'PIRATE SHIP ', 'HALLOWEEN PARTY', 'COOKIE POP', 'SHINING STARS', 'STONE AGE', 'WESTERN RANCH STORY', 'MONEY FEVER', 'TREASURE ISLAND', 'GOLDEN TREE',
        'SEA WORLD', 'RANCH STORY', 'CIRCUS', 'FIVE DRAGON', 'WEALTH', 'AZTEC', 'CRYSTAL', 'GARDEN', 'GREEN LIGHT', 'VICTORY', 'DRAGON GOLD', 'BOYKING', 'SEA CAPTAIN', 'FAME',
        'COYOTE CASH', 'BIG SHOT', 'CLEOPATRA', 'GIRLS', 'PAYDIRT', 'WILD FOX', 'PROSPERITY', 'WONG CHOY', 'HIGH WAY', 'ZHAO CAI JIN BAO', 'GREAT STARS', 'NIAN NIAN YOU YU ',
        'KIMOCHI', 'CAPTAIN', 'GREEN', 'IRISH LUCK', 'GOLDEN LOTUS', 'SPARTAN', 'FRUIT', 'AFRICAN', 'THE DISCOVERY', 'BONUS BEARS', 'GREAT BLUE', 'SAMURAI'
    ]
}

const listMega = () => {
    return [
        'WITCH', 'TOPGUN', 'FOOTBALL', 'EASTER', 'DASHENGNAOHAI', 'LIKUIPIYU', 'SUNWUKONG', 'JIN QIAN WA', 'FORTUNE PANDA', 'ROBIN HOOD', 'ALICE', 'SEASONS', 'PAN JIN LIAN',
        'MAGICAL SPIN', 'PIRATE SHIP ', 'HALLOWEEN PARTY', 'COOKIE POP', 'SHINING STARS', 'STONE AGE', 'WESTERN RANCH STORY', 'MONEY FEVER', 'TREASURE ISLAND', 'GOLDEN TREE',
        'SEA WORLD', 'RANCH STORY', 'CIRCUS', 'FIVE DRAGON', 'WEALTH', 'AZTEC', 'CRYSTAL', 'GARDEN', 'GREEN LIGHT', 'VICTORY', 'DRAGON GOLD', 'BOYKING', 'SEA CAPTAIN', 'FAME',
        'COYOTE CASH', 'BIG SHOT', 'CLEOPATRA', 'GIRLS', 'PAYDIRT', 'WILD FOX', 'PROSPERITY', 'WONG CHOY', 'HIGH WAY', 'ZHAO CAI JIN BAO', 'GREAT STARS', 'NIAN NIAN YOU YU ',
        'KIMOCHI', 'CAPTAIN', 'GREEN', 'IRISH LUCK', 'GOLDEN LOTUS', 'SPARTAN', 'FRUIT', 'AFRICAN', 'THE DISCOVERY', 'BONUS BEARS', 'GREAT BLUE', 'SAMURAI'
    ]
}

const listPussy = () => {
    return [
        'BULL FIGHT', 'JIN HOU WANG', 'EPIC APE', 'TIGER CLAW', 'LUCKY PANDA', 'WARRIORS GOLD', 'GAELIC LUCK', 'LIE YAN ZUAN SHI', 'ACE GODS/KING OF OLYMPUS', 'XUAN PU LIAN HUAN',
        'GHOS\'TS OF CHRISTMAS', 'MARILYN MONREO', 'YUN CONG LONG', 'CAPTAIN TREASURE', 'ARCHER', 'GREATBLUE', 'DOLPHIN', 'BONUS BEARS', 'LAND OF GOLD', 'SANTA SURPRISE', 'JIN HOU WANG',
        'CAPTAINPRO', 'HIGHWAY KING', 'BUFFALO BLITZ', 'GREAT BLUE', 'TREX', 'BIG SHOT', 'COYOTE CASH', 'FORTUNE PANDA', 'ICELAND', 'CAPTAIN', 'VICTORY', 'TALLYHO', 'DOLPHIN REEF',
        'BOY KING', 'WHITE KING', 'BANANA MONKEY', 'THREE KINGDOMS', 'HIGHWAY KING PRO', 'TOP GUN']
}

const listXe = () => {
    return [
        'OH MY HERO', 'ANCIENT FOREST', 'LICENSE TO WIN', 'BISON RAMPAGE 2', 'GOLD RUSH', 'LUPIN', 'FOOTBALL', 'MONEY', 'JIN QIAN WA', 'FORTUNE PANDA', 'ROBIN HOOD', 'ALICE',
        'AFRICAN WILDLIFE', 'SEASONS GREETINGS', 'LAURA', 'PIRATE', 'AMAZON', 'ALADDIN', 'DOLPHIN', 'JIN PING MAI 2', 'BULLS', 'UNICORN 2', 'LI KUI PI YU', 'MAGICAL SPINS',
        'DA SHENG NAO HAI', 'FAIRY GARDEN PLUS', 'CIRCUS', 'FENG SHEN', 'THREE KINGDOM', 'WATER MARGIN', 'FIVE DRAGON', 'WEALTH TREASURE', 'AZTEC', 'CRYSTAL WATERS',
        'ENCHANTED GARDEN', 'GREEN LIGHT', 'VICTORY', 'POLAR ADVENTURES', 'DRAGON GOLD', 'TALLY HO', 'FORTUNE', 'ORIENT EXPRESS', 'RALLY', 'MYSTICAL DRAGON', 'SEA CAPTAIN',
        'COYOTE CASH', 'T-REX', 'GLAMOUROUS WORLD', 'PAY DIRT', 'FAME', 'BIG SHOT', 'CLEOPATRA', 'TRIPLE TWISTER', 'STRIPPER NIGHT', 'UNICORN 2', 'GOLDEN SLUT', 'ICELAND',
        'JAPAN', 'AMAZING THAILAND', 'GREAT CHINA', 'INDIA', 'GOLDEN LOTUS', 'BIG PROSPERITY', 'WONG CHOY', 'HIGHWAY', 'ZHAO CAI JIN BAO', 'GREAT STARS', 'KIMOCHI', 'TOUCHDOWN 2',
        'NIAN NIAN YOU YU', 'CAPTAINS TREASURE', 'SPARTAN', 'SILVER BULLETS', 'SAFARI HEAT', 'THAI PARADISE', 'GREAT BLUE', 'IRISH LUCK', 'DISCOVERY', 'DOLPHIN REFF'
    ]
}

// EXPORT FUNCTION
export {listKiss, listMega, listPussy, listXe};