// LIST ALL GAMES
const listKiss = () => {
    return [
        'WOLF HUNTERS', 'DRAGON MAIDEN', 'STEAM TOWER', 'SUN WU KONG', 'WITCH', 'FOOTBALL', 'TOP GUN', 'EASTER', 'JIN QIAN WA', 'FORTUNE PANDA', 'ROBIN HOOD', 'ALICE',
        'AFRICAN WILDLIFE', 'SEASONS GREETINGS', 'LAURA', 'AMAZON', 'ALADDIN', 'DOLPHIN', 'PAN JIN LIAN', 'MAGICAL SPIN', 'PIRATE SHIP', 'HALLOWEEN PARTY', 'COOKIE POP',
        'SHINING STARS', 'FAIRY GARDEN', 'STONE AGE', 'WESTERN RANCH STORY', 'MONEY FEVER', 'TREASURE ISLAND', 'GOLDEN TREE', 'RANCH STORY', 'SEA WORLD', 'CIRCUS',
        'FENG SHEN', 'THREE KINGDOM', 'SWATER MARGIN', 'GOD OF WEALTH', 'FIVE DRAGON', 'WEALTH', 'AZTEC', 'CRYSTAL', 'GARDEN', 'GREEN LIGHT', 'VICTORY', 'DRAGON GOLD',
        'TALLY HO', 'FORTUNE', 'ORIENT', 'RALLY', 'BOYKING', 'DRAGON', 'SEA CAPTAIN', 'COYOTE CASH', 'T-REX', 'FASHION', 'PAY DIRT', 'FAME', 'BIG SHOT', 'CLEOPATRA',
        'TWISTER', 'GIRLS', 'GOLDEN SLUT', 'EMPEROR GATE', 'ICELAND', 'JAPAN', 'BOXING', 'PANDA', 'INDIA', 'WILD FOX', 'GOLDEN LOTUS', 'PROSPERITY', 'WONG CHOY',
        'HIGH WAY', 'ZHAO CAI JIN BAO', 'GREAT STARS', 'KIMOCHI', 'NIAN NIAN YOU YU', 'CAPTAIN', 'SPARTAN', 'SILVER', 'PANTHER MOON', 'SAFARI HEAT', 'THAI', 'BONUS BEARS',
        'CHERRY LOVE', 'GREAT BLUE', 'IRISH LUCK', 'THE DISCOVERY', 'SPARTA', 'FRUIT', 'GOLDEN TOUR', 'A NIGHT OUT', 'SAMURAI', 'DOLPHIN REEF'
    ]
}

const listMega = () => {
    return [
        'WITCH', 'TOPGUN', 'FOOTBALL', 'EASTER', 'DASHENGNAOHAI', 'SUNWUKONG', 'JIN QIAN WA', 'FORTUNE PANDA', 'ROBIN HOOD', 'ALICE', 'SEASONS', 'PAN JIN LIAN',
        'MAGICAL SPIN', 'PIRATE SHIP ', 'HALLOWEEN PARTY', 'COOKIE POP', 'SHINING STARS', 'STONE AGE', 'WESTERN RANCH STORY', 'MONEY FEVER', 'TREASURE ISLAND', 'GOLDEN TREE',
        'SEA WORLD', 'RANCH STORY', 'CIRCUS', 'FIVE DRAGON', 'WEALTH', 'AZTEC', 'CRYSTAL', 'GARDEN', 'GREEN LIGHT', 'VICTORY', 'DRAGON GOLD', 'BOYKING', 'SEA CAPTAIN', 'FAME',
        'COYOTE CASH', 'BIG SHOT', 'CLEOPATRA', 'GIRLS', 'PAYDIRT', 'WILD FOX', 'PROSPERITY', 'WONG CHOY', 'HIGH WAY', 'ZHAO CAI JIN BAO', 'GREAT STARS', 'NIAN NIAN YOU YU ',
        'KIMOCHI', 'CAPTAIN', 'GREEN', 'IRISH LUCK', 'GOLDEN LOTUS', 'SPARTAN', 'FRUIT', 'AFRICAN', 'THE DISCOVERY', 'BONUS BEARS', 'GREAT BLUE', 'SAMURAI'
    ]
}

const listPussy = () => {
    return [
        'BULL FIGHT', 'JIN HOU WANG', 'EPIC APE', 'TIGER CLAW', 'LUCKY PANDA', 'WARRIORS GOLD', 'GAELIC LUCK', 'LIE YAN ZUAN SHI', 'ACE GODS/KING OF OLYMPUS', 'XUAN PU LIAN HUAN',
        'GHOS\'TS OF CHRISTMAS', 'MARILYN MONREO', 'YUN CONG LONG', 'CAPTAIN TREASURE', 'ARCHER', 'GREATBLUE', 'DOLPHIN', 'BONUS BEARS', 'LAND OF GOLD', 'SANTA SURPRISE', 'JIN HOU WANG',
        'CAPTAINPRO', 'HIGHWAY KING', 'BUFFALO BLITZ', 'GREAT BLUE', 'TREX', 'BIG SHOT', 'COYOTE CASH', 'FORTUNE PANDA', 'ICELAND', 'CAPTAIN', 'VICTORY', 'TALLYHO', 'DOLPHIN REEF',
        'BOY KING', 'WHITE KING', 'BANANA MONKEY', 'THREE KINGDOMS', 'HIGHWAY KING PRO', 'TOP GUN']
}

const listXe = () => {
    return [
        'OH MY HERO', 'ANCIENT FOREST', 'LICENSE TO WIN', 'BISON RAMPAGE 2', 'GOLD RUSH', 'LUPIN', 'FOOTBALL', 'MONEY', 'JIN QIAN WA', 'FORTUNE PANDA', 'ROBIN HOOD', 'ALICE',
        'AFRICAN WILDLIFE', 'SEASONS GREETINGS', 'LAURA', 'PIRATE', 'AMAZON', 'ALADDIN', 'DOLPHIN', 'JIN PING MAI 2', 'BULLS', 'UNICORN 2', 'MAGICAL SPINS',
        'DA SHENG NAO HAI', 'FAIRY GARDEN PLUS', 'CIRCUS', 'FENG SHEN', 'THREE KINGDOM', 'WATER MARGIN', 'FIVE DRAGON', 'WEALTH TREASURE', 'AZTEC', 'CRYSTAL WATERS',
        'ENCHANTED GARDEN', 'GREEN LIGHT', 'VICTORY', 'POLAR ADVENTURES', 'DRAGON GOLD', 'TALLY HO', 'FORTUNE', 'ORIENT EXPRESS', 'RALLY', 'MYSTICAL DRAGON', 'SEA CAPTAIN',
        'COYOTE CASH', 'T-REX', 'GLAMOUROUS WORLD', 'PAY DIRT', 'FAME', 'BIG SHOT', 'CLEOPATRA', 'TRIPLE TWISTER', 'STRIPPER NIGHT', 'UNICORN 2', 'GOLDEN SLUT', 'ICELAND',
        'JAPAN', 'AMAZING THAILAND', 'GREAT CHINA', 'INDIA', 'GOLDEN LOTUS', 'BIG PROSPERITY', 'WONG CHOY', 'HIGHWAY', 'ZHAO CAI JIN BAO', 'GREAT STARS', 'KIMOCHI', 'TOUCHDOWN 2',
        'NIAN NIAN YOU YU', 'CAPTAINS TREASURE', 'SPARTAN', 'SILVER BULLETS', 'SAFARI HEAT', 'THAI PARADISE', 'GREAT BLUE', 'IRISH LUCK', 'DISCOVERY', 'DOLPHIN REFF'
    ]
}

// EXPORT FUNCTION
export {listKiss, listMega, listPussy, listXe};
